### PR TITLE
Use @var instead of @property in class-property doc-blocks

### PR DESCRIPTION
**Pull request by mkrauser**
see #97

### CODE REVIEW

**Comment by mkrauser** [comment]
I just saw that the VarTag-Class was added in Zend Code 3.3.2, which requires php 7.1. 
This seems like a big bump of the requirements. But it's your decision

**Comment by goetas** [comment]
Here is a difficult decision, this project is used mainly on soap/xml related projects ... that deal often with legacy stuff... this still stuck to php 5.x...

Maybe this is a good push for them to update!

**Comment by mkrauser** [comment]
@goetas Since only >= php 7.1 is officially supported, I would bump the requirements. 
I bet the users who are still using php 5.x are already having problems anyway. And if they want/need to, they can still use older versions.

**Comment by goetas** [comment]
Alright!

**Pull request merged**
